### ISSUE TITLE
Event Hubs trigger doesn't support batch trigger

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-library#14] opened 2018-06-13 17:48 UTC
_From @jeffhollan on June 13, 2018 12:14_

The best practice for running functions at high scale is to pull in a batch of messages in a single execution (`EventData[]`).  For javascript this is described in the function.json as:

```json
{
...
"cardinality": "many"
}
```

1. The Java attribute should allow for a configurable flag to set cardinality to many
  * The generated function.json should include `"cardinality": "many"`
1. The host should be able to send and have serialized `EventData[]` to the Java worker

@asavaritayal @pragnagopa as FYI

_Copied from original issue: Azure/azure-functions-java-worker#122_

**Comment by mhoeger** [comment] 2018-06-27 17:58
FYI i think this is a dupe of https://github.com/Azure/azure-functions-host/issues/2815

**Comment by jeffhollan** [comment] 2018-06-27 18:02
@mhoeger intresting - it sounds like the default in v2 would be `many` if cardinality omitted? I think this makes sense.  Actually what I think this will do is also break all Java Event Hub triggers.  The issue today is that the Java language worker doesn't appear to have a good way to receive a batch of messages even if you force cardinality to be many.  @pragnagopa that likely means this item needs to be done before the item @mhoeger checked in gets completed (with appropriate defaults) if we don't want Event Hubs to be broken in Java.

**Closed** 2018-08-13 16:16 UTC
Labels: functions-v2-GA-shouldhave
